name: Build

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          path: website
      - uses: actions/checkout@v4
        with:
          repository: messageformat/messageformat
          path: messageformat

      - run: rm -rf *
        working-directory: website

      - run: npm ci
        working-directory: messageformat
      - run: npm run build -w mf1/packages/parser -w mf1/packages/date-skeleton -w mf1/packages/number-skeleton
        working-directory: messageformat
      - run: npx typedoc --cleanOutputDir false --out ../website/
        working-directory: messageformat

      - name: git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - run: git add .
        working-directory: website
      - name: git commit & push any changes
        run: |
          git diff-index --quiet HEAD || (git commit -m "Update from messageformat @ $(cd ../messageformat && git rev-parse --short HEAD)" && git push)
        working-directory: website
